[build]
  # Vite production build
  command = "npm run build"
  # Directory containing generated assets
  publish = "dist"
  # Netlify Functions source (create folder if functions are added)
  functions = "netlify/functions"

[[redirects]]
  # SPA fallback for React Router / client-side navigation
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"